                ---
title: "Student`s t-test"

output:html_document: 
css: newsprint.css
number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```
## 单样本t检验

当σ未知且样本含量较小时（n<60），理论上要求t检验的样本随机地取自正态分布的总体，两小样本均数比较时还要求两样本所对应的两总体方差相等（$σ_1^2=σ_2^2$），即方差齐性。在实际应用时，如与上述条件略有偏离，对结果亦影响不大。
```{r}
# t.test(x, y = NULL, alternative = c("two.sided", "less", "greater"), mu = 0, paired = FALSE, var.equal = FALSE, conf.level = 0.95, ...)
# 若仅出现数据x，则进行单样本t检验；若出现数据x和y，则进行二样本的t检验；alternative = c("two.sided", "less", "greater")用于指定所求置信区间的类型；alternative = “two.sided”是缺省值，表示求置信区间；alterna = “less”表示求置信上限；alternative = “greater”表示求置信下限。mu表示均值，它仅在假设检验中起作用，默认值为0.
```

## 配对样本t检验
```{r}
g_l <- c(0.840, 0.591, 0.674, 0.632, 0.687, 0.978, 0.750, 0.730, 1.2, 0.870)
fat <- c(0.58, 0.509, 0.5, 0.316, 0.337, 0.517, 0.454, 0.512, 0.997, 0.506)
t.test(g_l, fat, paired = TRUE)
```

## 两样本t检验

### 总体方差相等的t检验
```{r}
ak <- c(-0.70, -5.60, 2.00, 2.80, 0.70, 3.50, 4.00, 5.80, 7.10, -0.50, 2.50, -1.60, 1.70, 3.00, 0.40, 4.50, 4.60, 2.50, 6.00, -1.40)
bt <- c(3.70, 6.5, 5, 5.2, 0.8, 0.2, 0.6, 3.4, 6.6, -1.10, 6, 3.80, 2.0, 1.6, 2, 2.2, 1.2, 3.1, 1.7, -2)
t.test(ak,bt, var.equal = TRUE)
```

### 两总体方差不等的t检验
进行两小样本均数比较，若两总体方差不等，即$σ_1^2=σ_2^2$时，可采用数据变换，或近似t检验（seperate variance estimation t-test）——t`检验或秩转换的非参数检验。
t`检验有Cochran&Cox近似t检验、Satterthwaite近似t检验及Welch近似t检验，R中t.test()函数使用的是Welch近似t检验。
```{r}
ak <- c(-0.70, -5.60, 2.00, 2.80, 0.70, 3.50, 4.00, 5.80, 7.10, -0.50, 2.50, -1.60, 1.70, 3.00, 0.40, 4.50, 4.60, 2.50, 6.00, -1.40)
bt <- c(3.70, 6.5, 5, 5.2, 0.8, 0.2, 0.6, 3.4, 6.6, -1.10, 6, 3.80, 2.0, 1.6, 2, 2.2, 1.2, 3.1, 1.7, -2)
t.test(ak,bt)
```




