---
title: "Parameter Estimation"

output:html_document: 
css: newsprint.css
number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```
## 点估计（矩法估计和极大似自然估计）

## 单正态总体参数的区间估计
### 均值μ的区间估计
#### 方差$σ^2$已知时μ的区间估计
```{r}
z.test <- function(x, n, sigma, alpha, u0=0, alternative = "two.sided"){
        options(digits = 4)
        result <- list()
        mean <- mean(x)
        z <- (mean - u0)/(sigma/sqrt(n))
        p <- pnorm(z, lower.tail = FALSE)
        result$mean <- mean
        result$z <- z
        result$p.value <- p
        if(alternative=="two.sided")
                result$p.value <- 2*pnorm(abs(z), lower.tail = FALSE)
        else if(alternative=="greater")
                result$p.value <- pnorm(z)
        result$conf.int <- c(
                mean - sigma*qnorm(1 - alpha/2, mean = 0, sd = 1, lower.tail = TRUE)/sqrt(n),
                mean + sigma*qnorm(1 - alpha/2, mean = 0, sd = 1, lower.tail = TRUE)/sqrt(n))
        result
}
```
```{r}
x <- c(175, 176, 173, 175, 174, 173, 173, 176, 173, 179)
result <- z.test(x, length(x), 1.5, 0.05)
result$conf.int
```
#### 方差$σ^2$未知时μ的置信区间

方差未知时，我们用t.test（）来求置信区间。t.test（）的调用格式如下：
```{r}
# t.test(x, y = NULL, alternative = c("two.sided", "less", "greater"), mu = 0, paired = FALSE, var.equal = FALSE, conf.level = 0.95, ...)
# 若仅出现数据x，则进行单样本t检验；若出现数据x和y，则进行二样本的t检验；alternative = c("two.sided", "less", "greater")用于指定所求置信区间的类型；alternative = “two.sided”是缺省值，表示求置信区间；alterna = “less”表示求置信上限；alternative = “greater”表示求置信下限。mu表示均值，它仅在假设检验中起作用，默认值为0.

x <- c(175, 176, 173, 175, 174, 173, 173, 176, 173, 179)
t.test(x)
t.test(x)$conf.int
```

#### 方差$σ^2$的区间估计
```{r}
chiq.var.test <- function(x, var, alpha, alternative = "two.sided"){
        options(digits = 4)
        result <- list()
        n <- length(x)
        v <- var(x)
        result$var <- v
        chi2 <- (n-1)*v/var
        result$chi2 <- chi2
        p <- pchisq(chi2, n-1)
        result$p.value <- p
        if(alternative =="less")
                result$p.value <- pchisq(chi2, n-1, lower.tail = F)
        else if(alternative == "two.sided")
                result$p.value <- 2*min(pchisq(chi2, n-1),
                                  pchisq(chi2, n-1, lower.tail = F))
        result$conf.int <- c((n-1)*v/qchisq(alpha/2, df = n-1, lower.tail = F),
                             (n-1)*v/qchisq(alpha/2, df = n-1, lower.tail = T))
        result
        
}
x <- c(175, 176, 173, 175, 174, 173, 173, 176, 173, 179)
chiq.var.test(x, var(x), alpha = 0.05)
```

## 两正态总体参数的区间估计

### 均值差μ1-μ2的置信区间

#### 两方差都已知时两均值的置信区间
```{r}
two.sample.ci <- function(x, y, conf.level = 0.95, sigma1, sigma2){
        options(digits = 4)
        m = length(x);n = length(y)
        xbar = mean(x) - mean(y)
        alpha = 1- conf.level
        zstar = qnorm(1 - alpha/2)*(sigma1/m + sigma2/n)^(1/2)
        xbar + c(-zstar , +zstar)
}
```
#### 两方差都未知但相等时两均值差的置信区间
在R中用t.test（）求两方差都未知但相等时两均值差的置信区间。

#### 两方差比$σ_1^2/σ_2^2$的置信区间
通过var.test（）函数可以直接用于求两正态总体方差比的置信区间。
```{r}
# var.test(x, y, ratio = 1, alternative = c("two.sided", "less", "greater"), conf.level = 0.95,...)
```